FROM openjdk:17
ARG JAR_FILE=build/libs/*.jar
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY src src
RUN chmod +x ./gradlew
COPY ${JAR_FILE} employment-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/employment-0.0.1-SNAPSHOT.jar"]