school:
  api-key: "ae97ff80ca48d0d9306cbbd2591a615a"
spring:
  profiles:
    include: oauth
  datasource:
    username: root
    password: win!@3456
    url: jdbc:mysql://localhost:3306/employment
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
