version: '3.9'

services:
  db:
    container_name: employment
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=qwer1234
      - MYSQL_DATABASE=employment
    ports:
      - "13306:3306"
    networks:
      - employment-network

networks:
  employment-network:
    driver: bridge